const StuData=[
    {
        "rollno":120,
        "name":"sanju",
        "city":"Bhopal",
        "fees":35000
    },
    {
        "rollno":121,
        "name":"manju",
        "city":"Bhopal",
        "fees":35000
    },
    {
        "rollno":122,
        "name":"ranju",
        "city":"Bhopal",
        "fees":35000
    },
    {
        "rollno":123,
        "name":"panju",
        "city":"Bhopal",
        "fees":35000
    },
    {
        "rollno":124,
        "name":"ganju",
        "city":"Bhopal",
        "fees":35000
    },
    {
        "rollno":125,
        "name":"janju",
        "city":"Bhopal",
        "fees":35000
    }
]
export default StuData;